carousel_enabled: 
  default: true

carousel_videos: 
  type: list
  default: "youtube, Jy5iHYArW9A|youtube, PhrdEOOpZxY|youtube, GN2sBZqTSEA"
  description: Accepts either YouTube or directly hosted MP4s. <br/> Format each option like so&#58; <br/><ul> <li><b>YouTube&#58;</b> youtube, Jy5iHYArW9A <br/> <em>Where Jy5iHYArW9A is the youtube video ID, present in the URL after v= and before any &</em></li> <li><b>MP4&#58;</b> mp4, https://example.com/video.mp4</li></ul>
  
feed_one_two_enabled:
  default: true

feed_one_title:
  default: Captured on Wyze

feed_one_category_slug:
  default: captured-on-wyze

feed_two_title:
  default: Ask the Community
  
feed_two_category_slug:
  default: ask-the-community

feed_three_enabled: 
   default: true

feed_three_title:
  default: Help these Wyze Members

feed_thee_category_id:
  default: 1

feed_three_topics_order:
  default: ascending
  type: enum
  choices: 
    - ascending
    - descending

